### ISSUE TITLE
Create File API

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/file-api#1]
Create a new file web service used to access files needed for web applications.

The files will be tracked in derived datasets created by the new derived dataset POST see: https://github.com/hubmapconsortium/ingest-ui/issues/71

**Comment by yuanzhou** [comment]
Currently the static files are served by Nginx via a mounted docker volume from host machine to the container that runs the gateway nginx.

For the next round, access control with globus token will be added to the gateway auth service for static files. Some files will be protected by requiring a valid globus token, which others may be public accessible.
